
// This file is generated by Firebase Studio.
"use client"

import * as React from "react"
import {
  ColumnDef,
  ColumnFiltersState,
  SortingState,
  VisibilityState,
  flexRender,
  getCoreRowModel,
  getFacetedRowModel,
  getFacetedUniqueValues,
  getFilteredRowModel,
  getPaginationRowModel,
  getSortedRowModel,
  useReactTable,
} from "@tanstack/react-table"

import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"

import { DataTablePagination } from "./data-table-pagination"
import { DataTableToolbar } from "./questoes-toolbar"
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"
import { useData } from "@/hooks/use-data"
import { Disciplina, Questao, Topico } from "@/types"
import { Skeleton } from "../ui/skeleton"
import { Card, CardContent } from "../ui/card"


interface DataTableProps<TData, TValue> {
  columns: ColumnDef<TData, TValue>[]
  disciplinas: Disciplina[]
  topicos: Topico[]
  isLoading: boolean;
}

export function QuestoesDataTable<TData, TValue>({
  columns: initialColumns,
  disciplinas,
  topicos,
  isLoading: isLoadingTaxonomy
}: DataTableProps<TData, TValue>) {
  const dataSource = useData();
  const queryClient = useQueryClient();

  const [rowSelection, setRowSelection] = React.useState({})
  const [columnVisibility, setColumnVisibility] =
    React.useState<VisibilityState>({})
  const [columnFilters, setColumnFilters] = React.useState<ColumnFiltersState>(
    []
  )
  const [sorting, setSorting] = React.useState<SortingState>([])

  const { data, isLoading: isLoadingQuestoes } = useQuery({
      queryKey: ['questoes'],
      queryFn: async () => {
          const result = await dataSource.list<Questao>('questoes_abcde1');
          return result as TData[];
      },
      placeholderData: (prev) => prev,
  });
  
  const getDisciplinaName = React.useCallback((id: string) => disciplinas?.find(d => d.id === id)?.nome || '...', [disciplinas]);
  const getTopicoName = React.useCallback((id: string) => topicos?.find(t => t.id === id)?.nome || '...', [topicos]);

  const columns = React.useMemo(() => initialColumns.map(col => {
    if ((col as any).accessorKey === 'disciplinaId') {
      return {
        ...col,
        cell: ({ row }: any) => getDisciplinaName(row.getValue('disciplinaId')),
      };
    }
    if ((col as any).accessorKey === 'topicoId') {
      return {
        ...col,
        cell: ({ row }: any) => getTopicoName(row.getValue('topicoId')),
      };
    }
    return col;
  }), [initialColumns, getDisciplinaName, getTopicoName]);


  const table = useReactTable({
    data: data ?? [],
    columns,
    autoResetPageIndex: false,
    state: {
      sorting,
      columnVisibility,
      rowSelection,
      columnFilters,
    },
    enableRowSelection: true,
    onRowSelectionChange: setRowSelection,
    onSortingChange: setSorting,
    onColumnFiltersChange: setColumnFilters,
    onColumnVisibilityChange: setColumnVisibility,
    getCoreRowModel: getCoreRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFacetedRowModel: getFacetedRowModel(),
    getFacetedUniqueValues: getFacetedUniqueValues(),
  })

  const isLoading = isLoadingTaxonomy || isLoadingQuestoes;

  return (
    <div className="space-y-4">
      <DataTableToolbar 
        table={table}
        disciplinas={disciplinas} 
        topicos={topicos}
      />
      <Card>
        <CardContent className="p-0">
            <Table>
            <TableHeader>
                {table.getHeaderGroups().map((headerGroup) => (
                <TableRow key={headerGroup.id}>
                    {headerGroup.headers.map((header) => {
                    return (
                        <TableHead key={header.id} colSpan={header.colSpan}>
                        {header.isPlaceholder
                            ? null
                            : flexRender(
                                header.column.columnDef.header,
                                header.getContext()
                            )}
                        </TableHead>
                    )
                    })}
                </TableRow>
                ))}
            </TableHeader>
            <TableBody>
                {isLoading ? (
                    Array.from({ length: 10 }).map((_, i) => (
                        <TableRow key={i}>
                        <TableCell colSpan={columns.length} className="h-12 text-center">
                            <Skeleton className="h-6 w-full" />
                        </TableCell>
                        </TableRow>
                    ))
                ) : (
                    table.getRowModel().rows?.length ? (
                    table.getRowModel().rows.map((row) => (
                        <TableRow
                        key={row.id}
                        data-state={row.getIsSelected() && "selected"}
                        >
                        {row.getVisibleCells().map((cell) => (
                            <TableCell key={cell.id}>
                            {flexRender(
                                cell.column.columnDef.cell,
                                cell.getContext()
                            )}
                            </TableCell>
                        ))}
                        </TableRow>
                    ))
                    ) : (
                    <TableRow>
                        <TableCell
                        colSpan={columns.length}
                        className="h-24 text-center"
                        >
                        Nenhuma questão encontrada.
                        </TableCell>
                    </TableRow>
                    )
                )}
            </TableBody>
            </Table>
        </CardContent>
      </Card>
      <DataTablePagination table={table} />
    </div>
  )
}
